// Code generated by MockGen. DO NOT EDIT.
// Source: timer.go
//
// Generated by this command:
//
//	mockgen -source=timer.go -destination=mock/timer.go -package=domain_mock
//

// Package domain_mock is a generated GoMock package.
package domain_mock

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockDomainTimer is a mock of DomainTimer interface.
type MockDomainTimer struct {
	ctrl     *gomock.Controller
	recorder *MockDomainTimerMockRecorder
}

// MockDomainTimerMockRecorder is the mock recorder for MockDomainTimer.
type MockDomainTimerMockRecorder struct {
	mock *MockDomainTimer
}

// NewMockDomainTimer creates a new mock instance.
func NewMockDomainTimer(ctrl *gomock.Controller) *MockDomainTimer {
	mock := &MockDomainTimer{ctrl: ctrl}
	mock.recorder = &MockDomainTimerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomainTimer) EXPECT() *MockDomainTimerMockRecorder {
	return m.recorder
}

// AsGoString mocks base method.
func (m *MockDomainTimer) AsGoString() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsGoString")
	ret0, _ := ret[0].(string)
	return ret0
}

// AsGoString indicates an expected call of AsGoString.
func (mr *MockDomainTimerMockRecorder) AsGoString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsGoString", reflect.TypeOf((*MockDomainTimer)(nil).AsGoString))
}

// AsGoTime mocks base method.
func (m *MockDomainTimer) AsGoTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsGoTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// AsGoTime indicates an expected call of AsGoTime.
func (mr *MockDomainTimerMockRecorder) AsGoTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsGoTime", reflect.TypeOf((*MockDomainTimer)(nil).AsGoTime))
}
