// Code generated by MockGen. DO NOT EDIT.
// Source: timer.go
//
// Generated by this command:
//
//	mockgen -source=timer.go -destination=mock/timer.go -package=domain_mock
//

// Package domain_mock is a generated GoMock package.
package domain_mock

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTimer is a mock of Timer interface.
type MockTimer struct {
	ctrl     *gomock.Controller
	recorder *MockTimerMockRecorder
}

// MockTimerMockRecorder is the mock recorder for MockTimer.
type MockTimerMockRecorder struct {
	mock *MockTimer
}

// NewMockTimer creates a new mock instance.
func NewMockTimer(ctrl *gomock.Controller) *MockTimer {
	mock := &MockTimer{ctrl: ctrl}
	mock.recorder = &MockTimerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimer) EXPECT() *MockTimerMockRecorder {
	return m.recorder
}

// AsGoString mocks base method.
func (m *MockTimer) AsGoString() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsGoString")
	ret0, _ := ret[0].(string)
	return ret0
}

// AsGoString indicates an expected call of AsGoString.
func (mr *MockTimerMockRecorder) AsGoString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsGoString", reflect.TypeOf((*MockTimer)(nil).AsGoString))
}

// AsGoTime mocks base method.
func (m *MockTimer) AsGoTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsGoTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// AsGoTime indicates an expected call of AsGoTime.
func (mr *MockTimerMockRecorder) AsGoTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsGoTime", reflect.TypeOf((*MockTimer)(nil).AsGoTime))
}
