package main

import (
	"log/slog"
	"os"

	echoSwagger "github.com/swaggo/echo-swagger"

	_ "todo/docs"
	"todo/internal/di"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
)

// docs is generated by Swag CLI, you have to import it.

// echo-swagger middleware

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /api/v1
func main() {
	// slogの初期化 json形式でログを出力
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))
	slog.SetDefault(logger)


	c, err := di.NewDITodoController()
	if err != nil {
		slog.Debug("failed to create controller", "err", err)
		panic(err)
	}


	e := echo.New()
	e.Use(middleware.CORSWithConfig(middleware.CORSConfig{
		AllowOrigins: []string{"*"},
		AllowHeaders: []string{echo.HeaderOrigin, echo.HeaderContentType, echo.HeaderAccept},
	}))
	  	  

	e.GET("/swagger/*", echoSwagger.WrapHandler)
	apiV1 := e.Group("/api/v1")
	apiV1.GET("/", c.GetHello())
	apiV1.GET("/todos", c.FindAllTodo())
	apiV1.POST("/todos", c.CreateTodo())
	apiV1.GET("/todos/:id", c.FindTodoByID())
	apiV1.PUT("/todos/:id", c.UpdateTodo())
	apiV1.DELETE("/todos/:id", c.DeleteTodo())



	e.Logger.Fatal(e.Start(":8080"))
}
